### ISSUE TITLE
[feat] 레벨뷰 레이아웃 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [Praise-Whale/Whale-iOS#18]
## 💙 제목
- 레벨뷰 레이아웃 구현

## 🚙 작업 브랜치
- levelView

## 📝 todo
- [x] 고래 레벨에 따른 roundGraph gage 구현
- [x] 고래 레벨 상세설명뷰 구현
- [x] 레벨 오를 시 popUp 구현
