### ISSUE TITLE
[feat] 칭찬레벨업시 레벨 탭에서 팝업카드 띄우기

### ISSUE THREAD

**Issue by hwangJi-dev** [Praise-Whale/Whale-iOS#24]
## 💙 제목
* 칭찬레벨 업시 레벨 탭에서 팝업카드 띄우기

## 🚙 작업 브랜치
- feat/#24

## 📝 todo
- [ ] 메인에서 Userdefaults로 레벨업여부true로(level탭용) 저장하기
- [ ] 레벨업여부가 true인 상태에서 레벨 탭을 들어온 순간 해당 레벨에 맞는 레벨업팝업 띄우기
- [ ] Userdefaults상태 false로 저장하기 (다음 레벨업시까지 유지)
