### ISSUE TITLE
[feat] 칭찬카드뷰 - 카드서랍 레이아웃 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [Praise-Whale/Whale-iOS#6]
## 💙 제목
* 칭찬카드뷰 - 카드서랍 레이아웃 구현

## 🚙 작업 브랜치
- feat/6

## 📝 todo
- [x] 전체 레이아웃 구현 
- [x] round SegmentView Custom
- [x] 카드서랍 클릭 시 하위 뷰 분기처리 후 연동
- [x] pickerView 커스텀 (년, 월만 표시 / 선택되는 컬러 custom)
- [x] 칭찬카드 collectionView 구현
